#!/sbin/sh
# 
# /system/addon.d/99-MIUICamV2.sh
# /system is formatted and reinstalled, then thes files are restored.
#

. /tmp/backuptool.functions

list_files() {
cat <<EOF
system/addon.d/98-MIUICamV2.shsystemp/addon.d/98-MIUICamV2.sh
systemp/addon.d/MIUICam_tweaks.sh
systemp/etc/device_features/whyred.xml
systemp/etc/media_profiles.xml
systemp/etc/permissions/android.hardware.camera.full.xml
systemp/etc/permissions/android.hardware.camera.raw.xml
systemp/etc/permissions/privapp-permissions-MIUIport.xml
systemp/framework/android-support-v13.jar
systemp/framework/android-support-v7-recyclerview.jar
systemp/framework/miuistatssdkshared.jar
systemp/framework/oat/arm/android-support-v13.odex
systemp/framework/oat/arm/android-support-v13.vdex
systemp/framework/oat/arm/android-support-v7-recyclerview.odex
systemp/framework/oat/arm/android-support-v7-recyclerview.vdex
systemp/framework/oat/arm/miuistatssdkshared.odex
systemp/framework/oat/arm/miuistatssdkshared.vdex
systemp/framework/oat/arm/volley.odex
systemp/framework/oat/arm/volley.vdex
systemp/framework/oat/arm/zxing.odex
systemp/framework/oat/arm/zxing.vdex
systemp/framework/oat/arm64/android-support-v13.odex
systemp/framework/oat/arm64/android-support-v13.vdex
systemp/framework/oat/arm64/android-support-v7-recyclerview.odex
systemp/framework/oat/arm64/android-support-v7-recyclerview.vdex
systemp/framework/oat/arm64/miuistatssdkshared.odex
systemp/framework/oat/arm64/miuistatssdkshared.vdex
systemp/framework/oat/arm64/volley.odex
systemp/framework/oat/arm64/volley.vdex
systemp/framework/oat/arm64/zxing.odex
systemp/framework/oat/arm64/zxing.vdex
systemp/framework/volley.jar
systemp/framework/zxing.jar
systemp/priv-app/MiuiCamera/lib/arm64/com.qualcomm.qti.imscmservice@1.0.so
systemp/priv-app/MiuiCamera/lib/arm64/com.qualcomm.qti.imscmservice@1.1.so
systemp/priv-app/MiuiCamera/lib/arm64/lib-imscamera.so
systemp/priv-app/MiuiCamera/lib/arm64/lib-imsvideocodec.so
systemp/priv-app/MiuiCamera/lib/arm64/lib-imsvt.so
systemp/priv-app/MiuiCamera/lib/arm64/lib-imsvtextutils.so
systemp/priv-app/MiuiCamera/lib/arm64/lib-imsvtutils.so
systemp/priv-app/MiuiCamera/lib/arm64/libblurbuster.so
systemp/priv-app/MiuiCamera/lib/arm64/libcamera2ndk.so
systemp/priv-app/MiuiCamera/lib/arm64/libcamera_metadata.so
systemp/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so
systemp/priv-app/MiuiCamera/lib/arm64/libcameraservice.so
systemp/priv-app/MiuiCamera/lib/arm64/libchromaflash.so
systemp/priv-app/MiuiCamera/lib/arm64/libdualcameraddm.so
systemp/priv-app/MiuiCamera/lib/arm64/libfilterfw.so
systemp/priv-app/MiuiCamera/lib/arm64/libfiltergenerator.so
systemp/priv-app/MiuiCamera/lib/arm64/libfilterpack_imageproc.so
systemp/priv-app/MiuiCamera/lib/arm64/libhazebuster.so
systemp/priv-app/MiuiCamera/lib/arm64/libimscamera_jni.so
systemp/priv-app/MiuiCamera/lib/arm64/libimsmedia_jni.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_blurbuster.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_chromaflash.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_dualcamera.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_filtergenerator.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_hazebuster.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_load_serinum.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_makeupV2.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_optizoom.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_panorama.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_resource_drm.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_seestraight.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_sharpshooter.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_stillmore.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_trackingfocus.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_trueportrait.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_truescanner_v2.so
systemp/priv-app/MiuiCamera/lib/arm64/libjni_ubifocus.so
systemp/priv-app/MiuiCamera/lib/arm64/libmiuiimageutilities.so
systemp/priv-app/MiuiCamera/lib/arm64/libmmcamera_faceproc.so
systemp/priv-app/MiuiCamera/lib/arm64/libmmcamera_faceproc2.so
systemp/priv-app/MiuiCamera/lib/arm64/libmorpho_group_portrait.so
systemp/priv-app/MiuiCamera/lib/arm64/libmorpho_groupshot.so
systemp/priv-app/MiuiCamera/lib/arm64/libmorpho_memory_allocator.so
systemp/priv-app/MiuiCamera/lib/arm64/libmorpho_panorama.so
systemp/priv-app/MiuiCamera/lib/arm64/libmorpho_panorama_gp.so
systemp/priv-app/MiuiCamera/lib/arm64/liboptizoom.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveBlobDescriptor.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveBlobDescriptor_stub.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveCommon.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveCommon_stub.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveFaceLandmarks.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveFaceLandmarks_stub.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveFaceRecognition.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveImageCorrection.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveObjectSegmentation.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveObjectTracker.so
systemp/priv-app/MiuiCamera/lib/arm64/libscveObjectTracker_stub.so
systemp/priv-app/MiuiCamera/lib/arm64/libscvePanorama.so
systemp/priv-app/MiuiCamera/lib/arm64/libscvePanorama_lite.so
systemp/priv-app/MiuiCamera/lib/arm64/libseestraight.so
systemp/priv-app/MiuiCamera/lib/arm64/libtrueportrait.so
systemp/priv-app/MiuiCamera/lib/arm64/libtruescanner.so
systemp/priv-app/MiuiCamera/lib/arm64/libts_detected_face_jni.so
systemp/priv-app/MiuiCamera/lib/arm64/libts_face_beautify_hal.so
systemp/priv-app/MiuiCamera/lib/arm64/libts_face_beautify_jni.so
systemp/priv-app/MiuiCamera/lib/arm64/libubifocus.so
systemp/priv-app/MiuiCamera/lib/arm64/libvip_channel.so
systemp/priv-app/MiuiCamera/lib/arm64/libvip_channel_iface.so
systemp/priv-app/MiuiCamera/lib/arm64/libxl_stat.so
systemp/priv-app/MiuiCamera/lib/arm64/libxl_thunder_iface.so
systemp/priv-app/MiuiCamera/lib/arm64/libxl_thunder_sdk.so
systemp/priv-app/MiuiCamera/lib/arm64/libXMFD_FaceDetect.so
systemp/priv-app/MiuiCamera/lib/arm64/libxt_native.so
systemp/priv-app/MiuiCamera/lib/arm64/vendor.qti.hardware.camera.device@1.0.so
systemp/priv-app/MiuiCamera/MiuiCamera.apk
systemp/priv-app/MiuiCamera/oat/arm64/MiuiCamera.odex
systemp/priv-app/MiuiCamera/oat/arm64/MiuiCamera.vdex
systemp/vendor/etc/acdbdata/adsp_avs_config.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb
systemp/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Bluetooth_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Codec_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_General_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Global_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Handset_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Hdmi_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Headset_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_Speaker_cal.acdb
systemp/vendor/etc/acdbdata/MTP/sdm660-tavil-snd-card/MTP_WCD9340_workspaceFile.qwsp
systemp/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb
systemp/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Bluetooth_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_General_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Global_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Handset_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Hdmi_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Headset_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_Speaker_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-snd-card-skush/QRD_SKUSH_workspaceFile.qwsp
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Bluetooth_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_General_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Global_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Handset_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Hdmi_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Headset_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_Speaker_cal.acdb
systemp/vendor/etc/acdbdata/QRD/sdm660-tasha-skus-snd-card/QRD_SKUS_workspaceFile.qwsp
systemp/vendor/etc/audio_platform_info.xml
systemp/vendor/etc/camera/age_gender_bg
systemp/vendor/etc/camera/camera_config.xml
systemp/vendor/etc/camera/crown_156_128.bin
systemp/vendor/etc/camera/csidtg_camera.xml
systemp/vendor/etc/camera/csidtg_chromatix.xml
systemp/vendor/etc/camera/dualcamera.png
systemp/vendor/etc/camera/dualcamera.png.bak
systemp/vendor/etc/camera/dualcamera_in.png
systemp/vendor/etc/camera/dualcamera_in.png.bak
systemp/vendor/etc/camera/face_goodly_208_180
systemp/vendor/etc/camera/face_ravishing_238_224
systemp/vendor/etc/camera/face_splendid_274_200
systemp/vendor/etc/camera/female_bg.png
systemp/vendor/etc/camera/female_icon.png
systemp/vendor/etc/camera/lf_facerank_model.bin
systemp/vendor/etc/camera/male_bg.png
systemp/vendor/etc/camera/male_icon.png
systemp/vendor/etc/camera/Miui-Light.ttf
systemp/vendor/etc/camera/MIUI_Time.ttf
systemp/vendor/etc/camera/model_zm.dlc
systemp/vendor/etc/camera/morpho_lowlight4.0.xml
systemp/vendor/etc/camera/people_gender.dat
systemp/vendor/etc/camera/score_bg.png
systemp/vendor/etc/camera/score_icon.png
systemp/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin
systemp/vendor/etc/camera/watermark_font_2300_3199.dat
systemp/vendor/etc/camera/whyred_imx376_ofilm_global_i_chromatix.xml
systemp/vendor/etc/camera/whyred_imx376_sunny_global_ii_chromatix.xml
systemp/vendor/etc/camera/whyred_imx486_ofilm_global_i_chromatix.xml
systemp/vendor/etc/camera/whyred_imx486_qtech_global_ii_chromatix.xml
systemp/vendor/etc/camera/whyred_ov13855_sunny_cn_i_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k2l7_ofilm_cn_i_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k2l7_qtech_cn_ii_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k3l8_ofilm_cn_ii_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k5e8_ofilm_cn_i_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k5e8_ofilm_global_i_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k5e8_qtech_cn_ii_chromatix.xml
systemp/vendor/etc/camera/whyred_s5k5e8_qtech_global_ii_chromatix.xml
systemp/vendor/etc/camera/yuv_test.xml
systemp/vendor/etc/media_profiles_V1_0.xml
systemp/vendor/etc/media_profiles_vendor.xml
systemp/vendor/etc/mixer_paths.xml
systemp/vendor/etc/mixer_paths_i2s.xml
systemp/vendor/etc/mixer_paths_mtp.xml
systemp/vendor/etc/mixer_paths_skus.xml
systemp/vendor/etc/mixer_paths_skush.xml
systemp/vendor/etc/mixer_paths_wcd9326.xml
systemp/vendor/etc/mixer_paths_wcd9335.xml
systemp/vendor/etc/mixer_paths_wcd9340.xml
systemp/vendor/etc/scve/facereco/gModel.dat
systemp/vendor/firmware/cpp_firmware_v1_10_0.fw
systemp/vendor/firmware/cpp_firmware_v1_12_0.fw
systemp/vendor/firmware/cpp_firmware_v1_1_1.fw
systemp/vendor/firmware/cpp_firmware_v1_1_6.fw
systemp/vendor/firmware/cpp_firmware_v1_2_0.fw
systemp/vendor/firmware/cpp_firmware_v1_4_0.fw
systemp/vendor/firmware/cpp_firmware_v1_5_0.fw
systemp/vendor/firmware/cpp_firmware_v1_5_1.fw
systemp/vendor/firmware/cpp_firmware_v1_5_2.fw
systemp/vendor/firmware/cpp_firmware_v1_6_0.fw
systemp/vendor/firmware/cpp_firmware_v1_8_0.fw
systemp/vendor/lib/hw/audio.primary.sdm660.so
systemp/vendor/lib64/hw/audio.primary.sdm660.so
EOF
}

case "$1" in
  backup)
    list_files | while read FILE DUMMY; do
      backup_file $S/"$FILE"
    done
  ;;
  restore)
    list_files | while read FILE REPLACEMENT; do
      R=""
      [ -n "$REPLACEMENT" ] && R="$S/$REPLACEMENT"
      [ -f "$C/$S/$FILE" ] && restore_file $S/"$FILE" "$R"
    done
		;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
  ;;
esac
