#!/sbin/sh
# 
# /system/addon.d/99-MIUICamV2.sh
# /system is formatted and reinstalled, then thes files are restored.
#

. /tmp/backuptool.functions

list_files() {
cat <<EOF
system/addon.d/98-MIUICamV2.sh
system/addon.d/MIUICam_tweaks.sh
